name: Combined Workflow
 
on:
  pull_request:
    branches:
      - main
      - both-actions-pass
 
jobs:
  build-and-push:
    name: Building Docker Image
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Building Docker image
        id: build_image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rr-ohini/cicd_assignment:latest
 
  validate-docker-image:
    name: Validating Docker Image
    runs-on: ubuntu-latest
    needs: build-and-push
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Pulling Docker image
        run: docker pull rr-ohini/cicd_assignment:latest
 
      - name: Run Docker container
        run: docker run rr-ohini/cicd_assignment:latest
 
      - name: Extract and validate score
        run: |
          output_score=$(docker run nivedyaps/cicd_assignment:latest | grep -oP '0\.\d+')
          if (( $(echo "$output_score > 0.30" | bc -l) )); then
            echo "Score is greater than 0.30"
            exit 0
          else
            echo "Score is less than or equal to 0.30"
            exit 1
          fi